-- 코드를 입력하세요
SELECT CATEGORY, Sum(SALES) as TOTAL_SALES
FROM BOOK
    JOIN BOOK_SALES ON BOOK.BOOK_ID = BOOK_SALES.BOOK_ID
WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY CATEGORY
ORDER BY CATEGORY